---
name: 'Run tests'
on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches: ['*']
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-24.04
    name: Lint codebase
    if: ${{ github.event_name != 'schedule' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
        with:
          extra-conf: |
            accept-flake-config = true
          diagnostic-endpoint: ''

      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run linters via pre-commit
        run: nix develop -c pre-commit run --all-files

  test:
    runs-on: ubuntu-24.04
    name: Run tests
    if: ${{ github.event_name != 'schedule' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Nx stuff
        uses: nrwl/nx-set-shas@v4

      - name: Run e2e tests (not failing for now)
        run: pnpm exec nx affected -t test build e2e-ci

  scan:
    runs-on: ubuntu-24.04
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          exit-code: '1'
          format: 'table'
          ignore-unfixed: true
          scan-ref: '.'
          scan-type: 'repo'
          severity: 'CRITICAL,HIGH'
          skip-dirs: '/root/.local/share/pnpm/store'
          timeout: 20m0s
        env:
          TRIVY_DISABLE_VEX_NOTICE: true
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true

  check_deps:
    runs-on: ubuntu-24.04
    name: Check for new dependencies
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Check for new dependencies
        uses: hiwelo/new-dependencies-action@1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-docs:
    runs-on: ubuntu-24.04
    name: Deploy docs to Cloudflare Pages
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the documentation
        run: pnpx nx build docs

      - name: Deploy to Cloudflare Pages
        if: (github.event_name == 'push') && (github.ref == 'refs/heads/main')
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy --branch dev
          packageManager: pnpm

      - name: Deploy to Cloudflare Pages
        if: ${{ github.event_name == 'pull_request' }}
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy --branch ${{ github.ref_name }}
          packageManager: pnpm
